# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='humbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/%Y/%m/%d/'),
        ),
    ]
